apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-device-plugin
labels:
  - pairs:
      app: sample-device-plugin

resources:
  - ../../base/devicepluginA-ds
  - ../../base/namespace

components:
  - ../../components/volumemounts

configMapGenerator:
  - name: device-a-configmap
    files:
      - devicepluginA/example_com_deviceA.yaml
