apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-device-plugin

resources:
  - ../../base/devicepluginC-ds

configMapGenerator:
  - name: device-c-configmap
    files:
      - example_com_deviceC.yaml

generatorOptions:
  labels:
    app: sample-device-plugin