apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-a-ds
spec:
  selector:
    matchLabels:
      name: device-plugin-a
  template:
    spec:
      serviceAccountName: sample-dp
      containers:
        - name: device-plugin-a-container
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-b-ds
spec:
  selector:
    matchLabels:
      name: device-plugin-b
  template:
    spec:
      serviceAccountName: sample-dp
      containers:
        - name: device-plugin-b-container
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-c-ds
spec:
  selector:
    matchLabels:
      name: device-plugin-c
  template:
    spec:
      serviceAccountName: sample-dp
      containers:
        - name: device-plugin-c-container
---
