apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-c-ds
spec:
  selector:
      matchLabels:
        name: device-plugin-c
  template:
    metadata:
      labels:
        name: device-plugin-c
    spec:
      hostNetwork: true
      containers:
      - name: device-plugin-a-container
        image: quay.io/aperevalov/device-plugin:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEVICE_RESOURCE_NAME
          value: "example.com/deviceC"
        volumeMounts:
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
