apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-dp
  namespace: sample-device-plugin
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
  resourceNames: ["privileged"]
