apiVersion: v1
kind: ConfigMap
metadata:
  name: device-a-configmap
  labels:
    app: sample-device-plugin
data:
  example_com_deviceA.yaml: |
      devices:
        kind-control-plane:
          - id: DevA1
            healthy: true
            numanode: 0
          - id: DevA2
            healthy: true
            numanode: 1
          - id: DevA3
            healthy: true
            numanode: 1
        '*':
          - id: DevA1
            healthy: true
            numanode: 0
          - id: DevA2
            healthy: true
            numanode: 0
          - id: DevA3
            healthy: true
            numanode: 0
