devicename: tty2
devices:
  kind-control-plane:
    - id: DevB1
      healthy: true
      numanode: 0
    - id: DevB2
      healthy: true
      numanode: 0
    - id: DevB3
      healthy: true
      numanode: 1
  '*':
    - id: DevB1
      healthy: true
      numanode: 1
    - id: DevB2
      healthy: true
      numanode: 1
    - id: DevB3
      healthy: true
      numanode: 1
