apiVersion: v1
kind: ConfigMap
metadata:
  name: device-c-configmap
data:
  example_com_deviceC.yaml: |
      devicename: tty1
      devices:
        kind-control-plane:
          - id: DevA1
            healthy: true
            numanode: -1
          - id: DevA2
            healthy: true
            numanode: -1
          - id: DevA3
            healthy: true
            numanode: -1
        '*':
          - id: DevA1
            healthy: true
            numanode: 0
          - id: DevA2
            healthy: true
            numanode: 0
          - id: DevA3
            healthy: true
            numanode: 0
