apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-device-plugin

resources:
  - devicepluginA-ds.yaml

configMapGenerator:
  - name: device-a-configmap
    files:
      - example_com_deviceA.yaml

generatorOptions:
  labels:
    app: sample-device-plugin
