apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-device-plugin
labels:
  - pairs:
      app: sample-device-plugin

resources:
  - ../../../base/namespace
  - ../../../base/devicepluginC-ds

configMapGenerator:
  - name: device-c-configmap
    files:
      - example_com_deviceC.yaml
