apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-device-plugin

bases:
- ../../base/devicepluginA-base
- ../../base/devicepluginB-base
- ../../base/devicepluginC-base

resources:
- namespace.yaml
