name: CI e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-ci:
    runs-on: ubuntu-22.04
    env:
      SAMPLE_DEVICE_PLUGIN_CONTAINER_IMAGE: quay.io/k8stopologyawareschedwg/sample-device-plugin:ci
      RUNTIME: docker
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup golang
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.18.1

      - name: show tool versions
        run: |
          go version
          kind version

      - name: build test binary
        run: |
          make build-e2e

      - name: build image
        run: |
          SAMPLE_DEVICE_PLUGIN_CONTAINER_IMAGE=${SAMPLE_DEVICE_PLUGIN_CONTAINER_IMAGE} RUNTIME=${RUNTIME} make image

      - name: create K8S kind cluster
        run: |
          # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
          # see image listing in https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
          kind create cluster --config=hack/kind-config-e2e.yaml --image kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
          kind load docker-image ${SAMPLE_DEVICE_PLUGIN_CONTAINER_IMAGE}

      - name: deploy sample-device-plugin
        run: |
          hack/ci-deploy-devices.sh
        
      - name: setup-info
        run: |
          kubectl describe -l app=sample-device-plugin configmaps || :
          kubectl describe -l app=sample-device-plugin daemonsets || :

      - name: run e2e test
        run: |
          make e2e-test
      
      
