name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      REPOOWNER: k8stopologyawareschedwg
      IMAGENAME: sample-device-plugin
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v3
      id: go
      with:
        go-version: 1.18

    - name: verify modules
      run: go mod verify

    - name: set release version env var
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: build image
      run: |
        REPOOWNER=${{ env.REPOOWNER }} IMAGENAME=${{ env.IMAGENAME }} IMAGETAG=${{ env.RELEASE_VERSION }} RUNTIME=docker make image

    - name: login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_ROBOTOKEN }}

    - name: publish image
      run: |
        docker push quay.io/${{ env.REPOOWNER }}/${{ env.IMAGENAME }}:${{ env.RELEASE_VERSION }}
